create table if not exists product_data_strings (
  id serial primary key,
  datenquelle TEXT,
  digitallink TEXT,
  produktbezeichnung TEXT ,
  produktionscharge TEXT,
  verpackungsdatum TEXT ,
  mhd TEXT,
  aufladewerttti TEXT,
  zieltemperatur TEXT,
  p1 TEXT,
  p2 TEXT,
  p3 TEXT,
  p4 TEXT,
  p5 TEXT,
  p6 TEXT,
  p7 TEXT,
  p8 TEXT,
  p9 TEXT,
  p10 TEXT,
  zeitstempel TEXT ,
  laenge TEXT,
  breite TEXT,
  rot TEXT,
  grün TEXT,
  blau TEXT,
  erwartete_temperatur TEXT,
  resthaltbarkeit TEXT
);
